# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-153557091-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Tutorials', path: 'menu', url: 'tutorials.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/davidemms'}
- {icon: 'twitter', link: 'https://twitter.com/David__Emms'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/david-emms-381a1850/'}
- {icon: 'envelope', link: 'mailto:david.emms@plants.ox.ac.uk'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'


